# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_folio',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
