# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170707_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_folio',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
