# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170711_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_folio',
            name='idST',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ST'),
        ),
        migrations.AlterUniqueTogether(
            name='st_folio',
            unique_together=set([('idST', 'idFolio')]),
        ),
    ]
